/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2019-03-31 03:12:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mymap_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:8080/geoserver/openlayers3/ol.css\" type=\"text/css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .ol-zoom {\r\n");
      out.write("          top: 52px;\r\n");
      out.write("        }\r\n");
      out.write("        .ol-toggle-options {\r\n");
      out.write("          z-index: 1000;\r\n");
      out.write("          background: rgba(255,255,255,0.4);\r\n");
      out.write("          border-radius: 4px;\r\n");
      out.write("          padding: 2px;\r\n");
      out.write("          position: absolute;\r\n");
      out.write("          left: 8px;\r\n");
      out.write("          top: 8px;\r\n");
      out.write("        }\r\n");
      out.write("        #updateFilterButton, #resetFilterButton {\r\n");
      out.write("          height: 22px;\r\n");
      out.write("          width: 22px;\r\n");
      out.write("          text-align: center;\r\n");
      out.write("          text-decoration: none !important;\r\n");
      out.write("          line-height: 22px;\r\n");
      out.write("          margin: 1px;\r\n");
      out.write("          font-family: 'Lucida Grande',Verdana,Geneva,Lucida,Arial,Helvetica,sans-serif;\r\n");
      out.write("          font-weight: bold !important;\r\n");
      out.write("          background: rgba(0,60,136,0.5);\r\n");
      out.write("          color: white !important;\r\n");
      out.write("          padding: 2px;\r\n");
      out.write("        }\r\n");
      out.write("        .ol-toggle-options a {\r\n");
      out.write("          background: rgba(0,60,136,0.5);\r\n");
      out.write("          color: white;\r\n");
      out.write("          display: block;\r\n");
      out.write("          font-family: 'Lucida Grande',Verdana,Geneva,Lucida,Arial,Helvetica,sans-serif;\r\n");
      out.write("          font-size: 19px;\r\n");
      out.write("          font-weight: bold;\r\n");
      out.write("          height: 22px;\r\n");
      out.write("          line-height: 11px;\r\n");
      out.write("          margin: 1px;\r\n");
      out.write("          padding: 0;\r\n");
      out.write("          text-align: center;\r\n");
      out.write("          text-decoration: none;\r\n");
      out.write("          width: 22px;\r\n");
      out.write("          border-radius: 2px;\r\n");
      out.write("        }\r\n");
      out.write("        .ol-toggle-options a:hover {\r\n");
      out.write("          color: #fff;\r\n");
      out.write("          text-decoration: none;\r\n");
      out.write("          background: rgba(0,60,136,0.7);\r\n");
      out.write("        }\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;\r\n");
      out.write("            font-size: small;\r\n");
      out.write("        }\r\n");
      out.write("        iframe {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 250px;\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("        /* Toolbar styles */\r\n");
      out.write("        #toolbar {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            padding-bottom: 0.5em;\r\n");
      out.write("        }\r\n");
      out.write("        #toolbar ul {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        #toolbar ul li {\r\n");
      out.write("            float: left;\r\n");
      out.write("            padding-right: 1em;\r\n");
      out.write("            padding-bottom: 0.5em;\r\n");
      out.write("        }\r\n");
      out.write("        #toolbar ul li a {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: smaller;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("            color: black;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        #toolbar ul li a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("        #toolbar ul li * {\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("        }\r\n");
      out.write("        #map {\r\n");
      out.write("            clear: both;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            width: 768px;\r\n");
      out.write("            height: 567px;\r\n");
      out.write("            border: 1px solid black;\r\n");
      out.write("        }\r\n");
      out.write("        #wrapper {\r\n");
      out.write("            width: 768px;\r\n");
      out.write("        }\r\n");
      out.write("        #location {\r\n");
      out.write("            float: right;\r\n");
      out.write("        }\r\n");
      out.write("        /* Styles used by the default GetFeatureInfo output, added to make IE happy */\r\n");
      out.write("        table.featureInfo, table.featureInfo td, table.featureInfo th {\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            font-size: 90%;\r\n");
      out.write("            padding: .2em .1em;\r\n");
      out.write("        }\r\n");
      out.write("        table.featureInfo th {\r\n");
      out.write("            padding: .2em .2em;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            background: #eee;\r\n");
      out.write("        }\r\n");
      out.write("        table.featureInfo td {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        table.featureInfo tr.odd td {\r\n");
      out.write("            background: #eee;\r\n");
      out.write("        }\r\n");
      out.write("        table.featureInfo caption {\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            font-size: 100%;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            padding: .2em .2em;\r\n");
      out.write("        }\r\n");
      out.write("       .ol-popup {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      background-color: white;\r\n");
      out.write("      -webkit-filter: drop-shadow(0 1px 4px rgba(0, 0, 0, 0.2));\r\n");
      out.write("      filter: drop-shadow(0 1px 4px rgba(0, 0, 0, 0.2));\r\n");
      out.write("      padding: 15px;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      border: 1px solid #cccccc;\r\n");
      out.write("      bottom: 12px;\r\n");
      out.write("      left: -50px;\r\n");
      out.write("      min-width: 280px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .ol-popup:after,\r\n");
      out.write("    .ol-popup:before {\r\n");
      out.write("      top: 100%;\r\n");
      out.write("      border: solid transparent;\r\n");
      out.write("      content: \" \";\r\n");
      out.write("      height: 0;\r\n");
      out.write("      width: 0;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      pointer-events: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .ol-popup:after {\r\n");
      out.write("      border-top-color: white;\r\n");
      out.write("      border-width: 10px;\r\n");
      out.write("      left: 48px;\r\n");
      out.write("      margin-left: -10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .ol-popup:before {\r\n");
      out.write("      border-top-color: #1a0505;\r\n");
      out.write("      border-width: 11px;\r\n");
      out.write("      left: 48px;\r\n");
      out.write("      margin-left: -11px;\r\n");
      out.write("      \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .ol-popup-closer {\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 2px;\r\n");
      out.write("      right: 8px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .ol-popup-closer:after {\r\n");
      out.write("      content: \"close\";\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- <script src=\"http://localhost:8080/geoserver/openlayers3/ol.js\" type=\"text/javascript\"></script> -->\r\n");
      out.write("    <script src=\"http://localhost:8080/ol.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- <script src=\"https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL\"></script> -->\r\n");
      out.write("    <title>OpenLayers map preview</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div id=\"toolbar\" style=\"display: none;\">\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a>WMS version:</a>\r\n");
      out.write("          <select id=\"wmsVersionSelector\" onchange=\"setWMSVersion(value)\">\r\n");
      out.write("            <option value=\"1.1.1\">1.1.1</option>\r\n");
      out.write("            <option value=\"1.3.0\">1.3.0</option>\r\n");
      out.write("          </select>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a>Tiling:</a>\r\n");
      out.write("          <select id=\"tilingModeSelector\" onchange=\"setTileMode(value)\">\r\n");
      out.write("            <option value=\"untiled\">Single tile</option>\r\n");
      out.write("            <option value=\"tiled\">Tiled</option>\r\n");
      out.write("          </select>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a>Antialias:</a>\r\n");
      out.write("          <select id=\"antialiasSelector\" onchange=\"setAntialiasMode(value)\">\r\n");
      out.write("            <option value=\"full\">Full</option>\r\n");
      out.write("            <option value=\"text\">Text only</option>\r\n");
      out.write("            <option value=\"none\">Disabled</option>\r\n");
      out.write("          </select>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a>Format:</a>\r\n");
      out.write("          <select id=\"imageFormatSelector\" onchange=\"setImageFormat(value)\">\r\n");
      out.write("            <option value=\"image/png\">PNG 24bit</option>\r\n");
      out.write("            <option value=\"image/png8\">PNG 8bit</option>\r\n");
      out.write("            <option value=\"image/gif\">GIF</option>\r\n");
      out.write("            <option id=\"jpeg\" value=\"image/jpeg\">JPEG</option>\r\n");
      out.write("            <option id=\"jpeg-png\" value=\"image/vnd.jpeg-png\">JPEG-PNG</option>\r\n");
      out.write("          </select>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a>Styles:</a>\r\n");
      out.write("          <select id=\"imageFormatSelector\" onchange=\"setStyle(value)\">\r\n");
      out.write("            <option value=\"\">Default</option>\r\n");
      out.write("          </select>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a>Width/Height:</a>\r\n");
      out.write("          <select id=\"widthSelector\" onchange=\"setWidth(value)\">\r\n");
      out.write("             <!--\r\n");
      out.write("             These values come from a statistics of the viewable area given a certain screen area\r\n");
      out.write("             (but have been adapted a litte, simplified numbers, added some resolutions for wide screen)\r\n");
      out.write("             You can find them here: http://www.evolt.org/article/Real_World_Browser_Size_Stats_Part_II/20/2297/\r\n");
      out.write("             --><option value=\"auto\">Auto</option>\r\n");
      out.write("                <option value=\"600\">600</option>\r\n");
      out.write("                <option value=\"750\">750</option>\r\n");
      out.write("                <option value=\"950\">950</option>\r\n");
      out.write("                <option value=\"1000\">1000</option>\r\n");
      out.write("                <option value=\"1200\">1200</option>\r\n");
      out.write("                <option value=\"1400\">1400</option>\r\n");
      out.write("                <option value=\"1600\">1600</option>\r\n");
      out.write("                <option value=\"1900\">1900</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <select id=\"heigthSelector\" onchange=\"setHeight(value)\">\r\n");
      out.write("                <option value=\"auto\">Auto</option>\r\n");
      out.write("                <option value=\"300\">300</option>\r\n");
      out.write("                <option value=\"400\">400</option>\r\n");
      out.write("                <option value=\"500\">500</option>\r\n");
      out.write("                <option value=\"600\">600</option>\r\n");
      out.write("                <option value=\"700\">700</option>\r\n");
      out.write("                <option value=\"800\">800</option>\r\n");
      out.write("                <option value=\"900\">900</option>\r\n");
      out.write("                <option value=\"1000\">1000</option>\r\n");
      out.write("            </select>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("              <a>Filter:</a>\r\n");
      out.write("              <select id=\"filterType\">\r\n");
      out.write("                  <option value=\"cql\">CQL</option>\r\n");
      out.write("                  <option value=\"ogc\">OGC</option>\r\n");
      out.write("                  <option value=\"fid\">FeatureID</option>\r\n");
      out.write("                  <option value=\"name\">Name</option>\r\n");
      out.write("                  <option value=\"name\">Pop</option>\r\n");
      out.write("              </select>\r\n");
      out.write("              <input type=\"text\" size=\"80\" id=\"filter\"/>\r\n");
      out.write("              <a id=\"updateFilterButton\" href=\"#\" onClick=\"updateFilter()\" title=\"Apply filter\">Apply</a>\r\n");
      out.write("              <a id=\"resetFilterButton\" href=\"#\" onClick=\"resetFilter()\" title=\"Reset filter\">Reset</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div id=\"popup\" class=\"ol-popup\">\r\n");
      out.write("        <a href=\"#\" id=\"popup-closer\" class=\"ol-popup-closer\"></a>\r\n");
      out.write("        <div id=\"popup-content\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- *********** -->\r\n");
      out.write("    <div>\r\n");
      out.write("      <p>enter:</p>\r\n");
      out.write("      <input type=\"text\" size=\"80\" id=\"filterByName\" value=\"成\"/> \r\n");
      out.write("      <a id=\"updateFilterByNameButton\" href=\"#\" onClick=\"updateFilterByName()\" title=\"Apply filter\">Search</a>\r\n");
      out.write("      <a id=\"resetFilterByNameButton\" href=\"#\" onClick=\"resetFilterByName()\" title=\"Reset filter\">Reset</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div>\r\n");
      out.write("      <p>enter a longitude:</p>\r\n");
      out.write("      <input type=\"text\" size=\"80\" id=\"longitude\" value=\"102\"/> \r\n");
      out.write("      <p>enter a latitude:</p>\r\n");
      out.write("      <input type=\"text\" size=\"80\" id=\"latitude\" value=\"31\"/> \r\n");
      out.write("      <a id=\"updateCoordButton\" href=\"#\" onClick=\"updateCoord()\" title=\"Apply filter\">Search</a>\r\n");
      out.write("      <a id=\"resetCoordButton\" href=\"#\" onClick=\"resetCoord()\" title=\"Reset filter\">Reset</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- *********** -->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div id=\"map\">\r\n");
      out.write("      <div class=\"ol-toggle-options ol-unselectable\"><a title=\"Toggle options toolbar\" onClick=\"toggleControlPanel()\" href=\"#toggle\">...</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- <div id=\"popup\" class=\"ol-popup\">\r\n");
      out.write("      <a href=\"#\" id=\"popup-closer\" class=\"ol-popup-closer\"></a>\r\n");
      out.write("      <div id=\"popup-content\"></div>\r\n");
      out.write("    </div> -->\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        <div id=\"location\"></div>\r\n");
      out.write("        <div id=\"scale\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"nodelist\">\r\n");
      out.write("        <em>Click on the map to get feature info</em>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/loadPage.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/searchCoord.js\" ></script>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/searchName.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
